### ISSUE TITLE
Windows *.bat files installed on Linux

### ISSUE THREAD

**Issue by tpkessler** [ROCm/HIPCC#107]
With the 5.6 release both the Linux and Windows wrappers for the perl scripts of `hipcc` and `hipconfig` are installed. This confuses the build system of ROCm math libraries like rocBLAS as they only expect either the Linux or the Windows script to be installed.

**Comment by rakicaleksandar1999** [comment]
This issue is fixed by [this](https://github.com/ROCm/clr/commit/df0f54ddf13eb7e1e5cc13f87c0ab8e05f7ca8c3) commit.

**Comment by lamb-j** [comment]
Looks like this was fixed by the commit above.

If you're still seeing this behavior, can you open a new Issue with the 'hipcc' tag at https://github.com/ROCm/llvm-project?

Thanks!
