### ISSUE TITLE
Duplicate symbols issue

### ISSUE THREAD

**Issue by tpadioleau** [ROCm/HIPCC#125]
I have a cmake project that looks like: `main` depends on two static libraries `lib1` and `lib2`, `lib2` depends also on `lib1` .

When compiled with `CMAKE_CXX_COMPILER=hipcc` and `CMAKE_CXX_FLAGS=-fgpu-rdc`, I end up with an error at link stage about duplicate symbols from `lib1`. Am I doing something wrong ?

I noticed that if relocatable device code is disabled, the executable links fine. If `main` does not depend on `lib1`, it links fine. If I use the HIP language support of cmake without `hipcc`, it links fine.

You can find attached a minimal [reproducer.zip](https://github.com/ROCm-Developer-Tools/HIPCC/files/12238459/reproducer.zip) to be compiled with `cmake -DCMAKE_CXX_COMPILER=hipcc ..`.

On my system `hipcc --version` gives:
```bash
HIP version: 5.4.22804-
AMD clang version 15.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ...
```

**Comment by kzhuravl** [comment]
cc @yxsamliu

**Comment by tpadioleau** [comment]
Do you have any update about the issue ?

**Comment by tpadioleau** [comment]
Seems to be working with `hipcc --version`:
```bash
HIP version: 5.5.30202-eaf00c0b
AMD clang version 16.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.5.1 23194 69ef12a7c3cc5b0ccf820bc007bd87e8b3ac3037)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ...
```
